spring:
  application:
    name: whatcha

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://whatchadb.cswkhwlfziph.ap-northeast-2.rds.amazonaws.com:3306/whatcha
    username: whatcha
    password: ${secret.mysql.password}

  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:
        auto: update
    show-sql: true

  config:
    import: optional:application-secret.yml

  cloud:
    aws:
      credentials:
        accessKey: ${secret.cloud.accessKey}
        secretKey: ${secret.cloud.secretKey}
      s3:
        bucket: whatchaa
      region:
        static: ap-northeast-2
      stack:
        auto: false

  data:
    redis:
      host: 172.31.37.49
      port: 6379
      password: ${secret.redis.password}

jwt:
  refresh-expired-in: '1296000000'  # Refresh Token (15)
  access-expired-in: '3600000' # Access Token (1)
  cookieName: refreshToken
  secret: ${secret-jwt.secret}
